image: "ghcr.io/gtk-rs/gtk4-rs/gtk4:latest"

before_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  - source $HOME/.cargo/env
  - rustup toolchain install nightly --profile minimal --allow-downgrade -c rustfmt
  - meson _build --prefix=/usr -Dlibadwaita:tests=false -Dlibadwaita:introspection=disabled -Dlibadwaita:examples=false -Dlibadwaita:vapi=false -Dlibpanel:introspection=disabled -Dlibpanel:install-examples=false -Dlibpanel:vapi=false
  - ninja -C _build install
  - git submodule update --init

build:
  script:
    - cargo build --all-features --examples
    - xvfb-run -a -s "-screen 0 1024x768x24" cargo test

