variables:
  # format is <branch>=<name>
  # the name is used in the URL
  # latest release must be at the top
  # (only relevant on main branch)
  RELEASES: |
    v0.2=0.2
    v0.1=v0.1

image: "ghcr.io/gtk-rs/gtk4-rs/gtk4:latest"

before_script:
  - dnf update -y && dnf install appstream-devel -y && dnf clean all -y
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  - source $HOME/.cargo/env
  - rustup toolchain install nightly --profile minimal --allow-downgrade -c rustfmt
  - meson setup _build --prefix=/usr -Dlibadwaita:tests=false -Dlibadwaita:introspection=disabled -Dlibadwaita:examples=false -Dlibadwaita:vapi=false -Dlibpanel:introspection=disabled -Dlibpanel:install-examples=false -Dlibpanel:vapi=false -Dlibpanel:docs=disabled
  - ninja -C _build install
  - git submodule update --init
  - curl --proto '=https' --tlsv1.2 -sSf -o gir-rustdoc.py
    https://gitlab.gnome.org/World/Rust/gir-rustdoc/-/raw/main/gir-rustdoc.py
  - chmod +x gir-rustdoc.py

build:
  script:
    - cargo build --features v1_4,gtk_v4_6,adw_v1_2 --examples
    - xvfb-run -a -s "-screen 0 1024x768x24" cargo test

docs:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # generate the docs
    - cargo install rustdoc-stripper
    - ./generator.py --embed-docs
    - rustup default nightly
    - eval $(./gir-rustdoc.py pre-docs)
    - cargo doc --all-features --no-deps -p libpanel -p libpanel-sys
    - mv target/doc/ docs
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  script:
    - ./gir-rustdoc.py html-index
    # main docs
    - mkdir public/git
    - mv docs public/git/docs
    # stable docs
    - ./gir-rustdoc.py docs-from-artifacts
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
