[package]
name = "libpanel"
version = "0.1.0"
edition = "2021"

[lib]
name = "libpanel"

[features]
dox = []

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
ffi = { package = "libpanel-sys", path = "./sys" }
glib = "0.14"
gio = "0.14"
gdk = { version = "0.3", package = "gdk4" }
gtk = { version = "0.3", package = "gtk4" }
libadwaita = { git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs" }
once_cell = "1.0"

[workspace]
members = ["sys"]
exclude = ["gir"]
