[package]
name = "libpanel"
version = "0.1.0"
edition = "2021"

[lib]
name = "libpanel"

[features]
dox = []
gtk_v4_2 = []
gtk_v4_4 = ["gtk_v4_2"]
gtk_v4_6 = ["gtk_v4_4"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
futures-core = { version = "0.3", default-features = false }
ffi = { package = "libpanel-sys", path = "./sys" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gdk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gdk4" }
gtk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gtk4" }
libadwaita = { git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs" }
once_cell = "1.0"

[workspace]
members = ["sys"]
exclude = ["gir"]
