[options]
girs_directories = [".", "gir-files"]
library = "Panel"
version = "1"
min_cfg_version = "1.0.0-alpha0"
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
trust_return_value_nullability = true
generate_builder = true

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Gtk",
    "Adw",
]

generate = [
  "Panel.*",
  "Panel.ActionMuxer",
  "Panel.Area",
  "Panel.Dock",
  "Panel.Frame",
  "Panel.FrameCallback",
  "Panel.FrameHeader",
  "Panel.FrameHeaderBar",
  "Panel.FrameSwitcher",
  "Panel.FrameTabBar",
  "Panel.Grid",
  "Panel.GridColumn",
  "Panel.Inhibitor",
  "Panel.OmniBar",
  "Panel.Paned",
  "Panel.Position",
  "Panel.SaveDialog",
  "Panel.Session",
  "Panel.Statusbar",
  "Panel.ThemeSelector",
  "Panel.ToggleButton",
  "Panel.Widget",
]

manual = [
  "Adw.MessageDialog",
  "GLib.Error",
  "GLib.Variant",
  "GLib.VariantType",
  "GObject.Object",
  "GObject.Value",
  "Gio.ActionGroup",
  "Gio.AsyncReadyCallback",
  "Gio.AsyncResult",
  "Gio.Cancellable",
  "Gio.Icon",
  "Gio.Menu",
  "Gio.MenuModel",
  "Gio.Resource",
  "Gio.Settings",
  "Gio.SettingsSchemaKey",
  "Gio.Task",
  "Gdk.RGBA",
  "Gtk.Accessible",
  "Gtk.Buildable",
  "Gtk.ConstraintTarget",
  "Gtk.Orientable",
  "Gtk.Popover",
  "Gtk.PopoverMenu",
  "Gtk.SelectionModel",
  "Gtk.Widget",
]

[[object]]
name = "Panel.GSettingsActionGroup"
status = "generate"
generate_builder = false
    [[object.function]]
    name = "new"
    manual = true

[[object]]
name = "Panel.LayeredSettings"
status = "generate"
generate_builder = false
    [[object.function]]
    name = "bind"
    manual = true
    [[object.function]]
    name = "bind_with_mapping"
    manual = true

[[object]]
name = "Panel.MenuManager"
status = "generate"
    [[object.function]]
    name = "add_filename"
    manual = true
    [[object.function]]
    name = "add_resource"
    manual = true

[[object]]
name = "Panel.SaveDelegate"
status = "generate"
manual_traits = ["SaveDelegateExtManual"]
    [[object.signal]]
    name = "save"
    manual = true
    doc_trait_name = "SaveDelegateExtManual"

[[object]]
name = "Panel.SessionItem"
status = "generate"
    [[object.function]]
    name = "has_metadata"
    manual = true
    [[object.function]]
    name = "metadata"
    manual = true
    [[object.function]]
    name = "set_metadata"
    manual = true

[[object]]
name = "Panel.Settings"
status = "generate"
generate_builder = false
    [[object.function]]
    name = "bind"
    manual = true
    [[object.function]]
    name = "bind_with_mapping"
    manual = true
    [[object.function]]
    name = "get_schema_id"
    manual = true
