[options]
girs_directories = [".", "gir-files"]
library = "Panel"
version = "1"
min_cfg_version = "1.0.0-alpha0"
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
trust_return_value_nullability = true
generate_builder = true

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Gtk",
    "Adw",
]

generate = [
  "Panel.*",
  "Panel.Dock",
  "Panel.DockPosition",
  "Panel.DockSwitcher",
  "Panel.Frame",
  "Panel.FrameCallback",
  "Panel.FrameHeader",
  "Panel.FrameHeaderBar",
  "Panel.FrameSwitcher",
  "Panel.FrameTabBar",
  "Panel.Grid",
  "Panel.GridColumn",
  "Panel.OmniBar",
  "Panel.Paned",
  "Panel.Statusbar",
  "Panel.ThemeSelector",
  "Panel.Widget",
]

manual = [
  "GLib.Error",
  "GLib.Variant",
  "GObject.Object",
  "GObject.Value",
  "Gio.ActionGroup",
  "Gio.AsyncReadyCallback",
  "Gio.AsyncResult",
  "Gio.Cancellable",
  "Gio.Icon",
  "Gio.MenuModel",
  "Gio.Resource",
  "Gio.Task",
  "Gdk.RGBA",
  "Gtk.Accessible",
  "Gtk.Buildable",
  "Gtk.ConstraintTarget",
  "Gtk.Orientable",
  "Gtk.Popover",
  "Gtk.PopoverMenu",
  "Gtk.SelectionModel",
  "Gtk.Widget",
]

[[object]]
name = "Panel.SaveDelegate"
status = "generate"
manual_traits = ["SaveDelegateExtManual"]
    [[object.signal]]
    name = "save"
    manual = true
    doc_trait_name = "SaveDelegateExtManual"
