// Generated by gir (https://github.com/gtk-rs/gir @ d7c0763cacbc)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 4d1189172a70)
// DO NOT EDIT

pub fn version() -> &'static str {
if cfg!(feature = "v1_4") {
        "1.4"
    } else if cfg!(feature = "v1_2") {
        "1.2"
    } else {
        "1"
    }
}
