// Generated by gir (https://github.com/gtk-rs/gir @ 10574a3693ac)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ b42700b30bb2)
// DO NOT EDIT

pub fn version() -> &'static str {
if cfg!(feature = "v1_4") {
        "1.4"
    } else if cfg!(feature = "v1_2") {
        "1.2"
    } else {
        "1"
    }
}
