// Generated by gir (https://github.com/gtk-rs/gir @ c8aeb47d4dd4)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ f106c667af5a)
// DO NOT EDIT

pub fn version() -> &'static str {
if cfg!(feature = "v1_4") {
        "1.4"
    } else if cfg!(feature = "v1_2") {
        "1.2"
    } else {
        "1"
    }
}
