// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    #[doc(alias = "PanelApplication")]
    pub struct Application(Object<ffi::PanelApplication, ffi::PanelApplicationClass>) @extends adw::Application, @implements gio::ActionGroup;

    match fn {
        type_ => || ffi::panel_application_get_type(),
    }
}

impl Application {
    pub const NONE: Option<&'static Application> = None;

    #[doc(alias = "panel_application_new")]
    pub fn new(application_id: &str, flags: gio::ApplicationFlags) -> Application {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::panel_application_new(
                application_id.to_glib_none().0,
                flags.into_glib(),
            ))
        }
    }
}
