// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use std::ffi::CStr;

#[doc(alias = "PANEL_VERSION_S")]
pub static VERSION_S: once_cell::sync::Lazy<&'static str> = once_cell::sync::Lazy::new(|| unsafe {
    CStr::from_ptr(ffi::PANEL_VERSION_S).to_str().unwrap()
});
#[doc(alias = "PANEL_WIDGET_KIND_ANY")]
pub static WIDGET_KIND_ANY: once_cell::sync::Lazy<&'static str> =
    once_cell::sync::Lazy::new(|| unsafe {
        CStr::from_ptr(ffi::PANEL_WIDGET_KIND_ANY).to_str().unwrap()
    });
#[doc(alias = "PANEL_WIDGET_KIND_DOCUMENT")]
pub static WIDGET_KIND_DOCUMENT: once_cell::sync::Lazy<&'static str> =
    once_cell::sync::Lazy::new(|| unsafe {
        CStr::from_ptr(ffi::PANEL_WIDGET_KIND_DOCUMENT)
            .to_str()
            .unwrap()
    });
#[doc(alias = "PANEL_WIDGET_KIND_UNKNOWN")]
pub static WIDGET_KIND_UNKNOWN: once_cell::sync::Lazy<&'static str> =
    once_cell::sync::Lazy::new(|| unsafe {
        CStr::from_ptr(ffi::PANEL_WIDGET_KIND_UNKNOWN)
            .to_str()
            .unwrap()
    });
#[doc(alias = "PANEL_WIDGET_KIND_UTILITY")]
pub static WIDGET_KIND_UTILITY: once_cell::sync::Lazy<&'static str> =
    once_cell::sync::Lazy::new(|| unsafe {
        CStr::from_ptr(ffi::PANEL_WIDGET_KIND_UTILITY)
            .to_str()
            .unwrap()
    });
