// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files
// DO NOT EDIT

use glib::translate::*;
use std::fmt;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "PanelDockPosition")]
pub enum DockPosition {
    #[doc(alias = "PANEL_DOCK_POSITION_START")]
    Start,
    #[doc(alias = "PANEL_DOCK_POSITION_END")]
    End,
    #[doc(alias = "PANEL_DOCK_POSITION_TOP")]
    Top,
    #[doc(alias = "PANEL_DOCK_POSITION_BOTTOM")]
    Bottom,
    #[doc(alias = "PANEL_DOCK_POSITION_CENTER")]
    Center,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for DockPosition {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "DockPosition::{}",
            match *self {
                Self::Start => "Start",
                Self::End => "End",
                Self::Top => "Top",
                Self::Bottom => "Bottom",
                Self::Center => "Center",
                _ => "Unknown",
            }
        )
    }
}

#[doc(hidden)]
impl IntoGlib for DockPosition {
    type GlibType = ffi::PanelDockPosition;

    fn into_glib(self) -> ffi::PanelDockPosition {
        match self {
            Self::Start => ffi::PANEL_DOCK_POSITION_START,
            Self::End => ffi::PANEL_DOCK_POSITION_END,
            Self::Top => ffi::PANEL_DOCK_POSITION_TOP,
            Self::Bottom => ffi::PANEL_DOCK_POSITION_BOTTOM,
            Self::Center => ffi::PANEL_DOCK_POSITION_CENTER,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::PanelDockPosition> for DockPosition {
    unsafe fn from_glib(value: ffi::PanelDockPosition) -> Self {
        skip_assert_initialized!();
        match value {
            ffi::PANEL_DOCK_POSITION_START => Self::Start,
            ffi::PANEL_DOCK_POSITION_END => Self::End,
            ffi::PANEL_DOCK_POSITION_TOP => Self::Top,
            ffi::PANEL_DOCK_POSITION_BOTTOM => Self::Bottom,
            ffi::PANEL_DOCK_POSITION_CENTER => Self::Center,
            value => Self::__Unknown(value),
        }
    }
}
