// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::{translate::*, value::FromValue, value::ToValue, StaticType, Type};
use std::fmt;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "PanelArea")]
pub enum Area {
    #[doc(alias = "PANEL_AREA_START")]
    Start,
    #[doc(alias = "PANEL_AREA_END")]
    End,
    #[doc(alias = "PANEL_AREA_TOP")]
    Top,
    #[doc(alias = "PANEL_AREA_BOTTOM")]
    Bottom,
    #[doc(alias = "PANEL_AREA_CENTER")]
    Center,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for Area {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "Area::{}",
            match *self {
                Self::Start => "Start",
                Self::End => "End",
                Self::Top => "Top",
                Self::Bottom => "Bottom",
                Self::Center => "Center",
                _ => "Unknown",
            }
        )
    }
}

#[doc(hidden)]
impl IntoGlib for Area {
    type GlibType = ffi::PanelArea;

    fn into_glib(self) -> ffi::PanelArea {
        match self {
            Self::Start => ffi::PANEL_AREA_START,
            Self::End => ffi::PANEL_AREA_END,
            Self::Top => ffi::PANEL_AREA_TOP,
            Self::Bottom => ffi::PANEL_AREA_BOTTOM,
            Self::Center => ffi::PANEL_AREA_CENTER,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::PanelArea> for Area {
    unsafe fn from_glib(value: ffi::PanelArea) -> Self {
        skip_assert_initialized!();
        match value {
            ffi::PANEL_AREA_START => Self::Start,
            ffi::PANEL_AREA_END => Self::End,
            ffi::PANEL_AREA_TOP => Self::Top,
            ffi::PANEL_AREA_BOTTOM => Self::Bottom,
            ffi::PANEL_AREA_CENTER => Self::Center,
            value => Self::__Unknown(value),
        }
    }
}

impl StaticType for Area {
    fn static_type() -> Type {
        unsafe { from_glib(ffi::panel_area_get_type()) }
    }
}

impl glib::value::ValueType for Area {
    type Type = Self;
}

unsafe impl<'a> FromValue<'a> for Area {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_enum(value.to_glib_none().0))
    }
}

impl ToValue for Area {
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_enum(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<Area> for glib::Value {
    #[inline]
    fn from(v: Area) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}
