// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files
// DO NOT EDIT

use crate::FrameHeader;
use glib::object::Cast;
use glib::object::ObjectType as ObjectType_;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    #[doc(alias = "PanelFrameSwitcher")]
    pub struct FrameSwitcher(Object<ffi::PanelFrameSwitcher, ffi::PanelFrameSwitcherClass>) @extends gtk::Widget, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget, gtk::Orientable, FrameHeader;

    match fn {
        type_ => || ffi::panel_frame_switcher_get_type(),
    }
}

impl FrameSwitcher {
    #[doc(alias = "panel_frame_switcher_new")]
    pub fn new() -> FrameSwitcher {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::panel_frame_switcher_new()).unsafe_cast() }
    }

    #[doc(alias = "panel_frame_switcher_get_background_rgba")]
    #[doc(alias = "get_background_rgba")]
    pub fn background_rgba(&self) -> Option<gdk::RGBA> {
        unsafe {
            from_glib_none(ffi::panel_frame_switcher_get_background_rgba(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "panel_frame_switcher_get_foreground_rgba")]
    #[doc(alias = "get_foreground_rgba")]
    pub fn foreground_rgba(&self) -> Option<gdk::RGBA> {
        unsafe {
            from_glib_none(ffi::panel_frame_switcher_get_foreground_rgba(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "panel_frame_switcher_set_background_rgba")]
    pub fn set_background_rgba(&self, background_rgba: Option<&gdk::RGBA>) {
        unsafe {
            ffi::panel_frame_switcher_set_background_rgba(
                self.to_glib_none().0,
                background_rgba.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "panel_frame_switcher_set_foreground_rgba")]
    pub fn set_foreground_rgba(&self, foreground_rgba: Option<&gdk::RGBA>) {
        unsafe {
            ffi::panel_frame_switcher_set_foreground_rgba(
                self.to_glib_none().0,
                foreground_rgba.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "background-rgba")]
    pub fn connect_background_rgba_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_background_rgba_trampoline<F: Fn(&FrameSwitcher) + 'static>(
            this: *mut ffi::PanelFrameSwitcher,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::background-rgba\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_background_rgba_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "foreground-rgba")]
    pub fn connect_foreground_rgba_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_foreground_rgba_trampoline<F: Fn(&FrameSwitcher) + 'static>(
            this: *mut ffi::PanelFrameSwitcher,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::foreground-rgba\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_foreground_rgba_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for FrameSwitcher {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for FrameSwitcher {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FrameSwitcher")
    }
}
