// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::{prelude::*, translate::*};
use std::fmt;

glib::wrapper! {
    #[doc(alias = "PanelGSettingsActionGroup")]
    pub struct GSettingsActionGroup(Object<ffi::PanelGSettingsActionGroup, ffi::PanelGSettingsActionGroupClass>) @implements gio::ActionGroup;

    match fn {
        type_ => || ffi::panel_gsettings_action_group_get_type(),
    }
}

impl GSettingsActionGroup {
    pub fn settings(&self) -> Option<gio::Settings> {
        glib::ObjectExt::property(self, "settings")
    }
}

impl fmt::Display for GSettingsActionGroup {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("GSettingsActionGroup")
    }
}
