// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::translate::*;

glib::wrapper! {
    #[doc(alias = "PanelInhibitor")]
    pub struct Inhibitor(Object<ffi::PanelInhibitor, ffi::PanelInhibitorClass>);

    match fn {
        type_ => || ffi::panel_inhibitor_get_type(),
    }
}

impl Inhibitor {
    #[doc(alias = "panel_inhibitor_uninhibit")]
    pub fn uninhibit(&self) {
        unsafe {
            ffi::panel_inhibitor_uninhibit(self.to_glib_none().0);
        }
    }
}
