// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

mod action_muxer;
pub use self::action_muxer::ActionMuxer;

mod dock;
pub use self::dock::Dock;

mod frame;
pub use self::frame::Frame;

mod frame_header;
pub use self::frame_header::FrameHeader;

mod frame_header_bar;
pub use self::frame_header_bar::FrameHeaderBar;

mod frame_switcher;
pub use self::frame_switcher::FrameSwitcher;

mod frame_tab_bar;
pub use self::frame_tab_bar::FrameTabBar;

mod gsettings_action_group;
pub use self::gsettings_action_group::GSettingsActionGroup;

mod grid;
pub use self::grid::Grid;

mod grid_column;
pub use self::grid_column::GridColumn;

mod inhibitor;
pub use self::inhibitor::Inhibitor;

mod layered_settings;
pub use self::layered_settings::LayeredSettings;

mod menu_manager;
pub use self::menu_manager::MenuManager;

mod omni_bar;
pub use self::omni_bar::OmniBar;

mod paned;
pub use self::paned::Paned;

mod position;
pub use self::position::Position;

mod save_delegate;
pub use self::save_delegate::SaveDelegate;

mod save_dialog;
pub use self::save_dialog::SaveDialog;

mod session;
pub use self::session::Session;

mod session_item;
pub use self::session_item::SessionItem;

mod settings;
pub use self::settings::Settings;

mod statusbar;
pub use self::statusbar::Statusbar;

mod theme_selector;
pub use self::theme_selector::ThemeSelector;

mod toggle_button;
pub use self::toggle_button::ToggleButton;

mod widget;
pub use self::widget::Widget;

mod enums;
pub use self::enums::Area;

pub mod functions;

mod constants;
pub use self::constants::VERSION_S;
pub use self::constants::WIDGET_KIND_ANY;
pub use self::constants::WIDGET_KIND_DOCUMENT;
pub use self::constants::WIDGET_KIND_UNKNOWN;
pub use self::constants::WIDGET_KIND_UTILITY;

#[doc(hidden)]
pub mod traits {
    pub use super::dock::DockExt;
    pub use super::frame::FrameExt;
    pub use super::frame_header::FrameHeaderExt;
    pub use super::grid::GridExt;
    pub use super::omni_bar::OmniBarExt;
    pub use super::save_delegate::SaveDelegateExt;
    pub use super::widget::WidgetExt;
}
#[doc(hidden)]
pub mod builders {
    pub use super::dock::DockBuilder;
    pub use super::frame::FrameBuilder;
    pub use super::frame_header_bar::FrameHeaderBarBuilder;
    pub use super::frame_switcher::FrameSwitcherBuilder;
    pub use super::frame_tab_bar::FrameTabBarBuilder;
    pub use super::grid::GridBuilder;
    pub use super::grid_column::GridColumnBuilder;
    pub use super::omni_bar::OmniBarBuilder;
    pub use super::paned::PanedBuilder;
    pub use super::position::PositionBuilder;
    pub use super::save_delegate::SaveDelegateBuilder;
    pub use super::save_dialog::SaveDialogBuilder;
    pub use super::session_item::SessionItemBuilder;
    pub use super::statusbar::StatusbarBuilder;
    pub use super::theme_selector::ThemeSelectorBuilder;
    pub use super::toggle_button::ToggleButtonBuilder;
    pub use super::widget::WidgetBuilder;
}
