// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

mod dock;
pub use self::dock::Dock;
pub use self::dock::DockBuilder;

mod dock_switcher;
pub use self::dock_switcher::DockSwitcher;
pub use self::dock_switcher::DockSwitcherBuilder;

mod frame;
pub use self::frame::Frame;
pub use self::frame::FrameBuilder;

mod frame_header;
pub use self::frame_header::FrameHeader;

mod frame_header_bar;
pub use self::frame_header_bar::FrameHeaderBar;
pub use self::frame_header_bar::FrameHeaderBarBuilder;

mod frame_switcher;
pub use self::frame_switcher::FrameSwitcher;
pub use self::frame_switcher::FrameSwitcherBuilder;

mod frame_tab_bar;
pub use self::frame_tab_bar::FrameTabBar;
pub use self::frame_tab_bar::FrameTabBarBuilder;

mod grid;
pub use self::grid::Grid;
pub use self::grid::GridBuilder;

mod grid_column;
pub use self::grid_column::GridColumn;
pub use self::grid_column::GridColumnBuilder;

mod save_delegate;
pub use self::save_delegate::SaveDelegate;
pub use self::save_delegate::SaveDelegateBuilder;

mod statusbar;
pub use self::statusbar::Statusbar;
pub use self::statusbar::StatusbarBuilder;

mod widget;
pub use self::widget::Widget;
pub use self::widget::WidgetBuilder;

mod enums;
pub use self::enums::DockPosition;

pub mod functions;

mod constants;
pub use self::constants::VERSION_S;
pub use self::constants::WIDGET_KIND_ANY;
pub use self::constants::WIDGET_KIND_DOCUMENT;
pub use self::constants::WIDGET_KIND_UNKNOWN;
pub use self::constants::WIDGET_KIND_UTILITY;

#[doc(hidden)]
pub mod traits {
    pub use super::dock::DockExt;
    pub use super::frame::FrameExt;
    pub use super::frame_header::FrameHeaderExt;
    pub use super::save_delegate::SaveDelegateExt;
    pub use super::widget::WidgetExt;
}
