// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files
// DO NOT EDIT

use glib::object::Cast;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "PanelStatusbar")]
    pub struct Statusbar(Object<ffi::PanelStatusbar, ffi::PanelStatusbarClass>) @extends gtk::Widget, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget;

    match fn {
        type_ => || ffi::panel_statusbar_get_type(),
    }
}

impl Statusbar {
    #[doc(alias = "panel_statusbar_new")]
    pub fn new() -> Statusbar {
        assert_initialized_main_thread!();
        unsafe { gtk::Widget::from_glib_none(ffi::panel_statusbar_new()).unsafe_cast() }
    }
}

impl Default for Statusbar {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for Statusbar {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Statusbar")
    }
}
