// Generated by gir (https://github.com/gtk-rs/gir @ ee37253c10af)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 923f9a1041f5)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) PANEL_DOCK_POSITION_BOTTOM);
    PRINT_CONSTANT((gint) PANEL_DOCK_POSITION_CENTER);
    PRINT_CONSTANT((gint) PANEL_DOCK_POSITION_END);
    PRINT_CONSTANT((gint) PANEL_DOCK_POSITION_START);
    PRINT_CONSTANT((gint) PANEL_DOCK_POSITION_TOP);
    PRINT_CONSTANT(PANEL_MAJOR_VERSION);
    PRINT_CONSTANT(PANEL_MICRO_VERSION);
    PRINT_CONSTANT(PANEL_MINOR_VERSION);
    PRINT_CONSTANT(PANEL_VERSION_S);
    PRINT_CONSTANT(PANEL_WIDGET_KIND_ANY);
    PRINT_CONSTANT(PANEL_WIDGET_KIND_DOCUMENT);
    PRINT_CONSTANT(PANEL_WIDGET_KIND_UNKNOWN);
    PRINT_CONSTANT(PANEL_WIDGET_KIND_UTILITY);
    return 0;
}
