// Generated by gir (https://github.com/gtk-rs/gir @ 10574a3693ac)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ b42700b30bb2)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PanelActionMuxerClass", sizeof(PanelActionMuxerClass), alignof(PanelActionMuxerClass));
    printf("%s;%zu;%zu\n", "PanelArea", sizeof(PanelArea), alignof(PanelArea));
    printf("%s;%zu;%zu\n", "PanelDock", sizeof(PanelDock), alignof(PanelDock));
    printf("%s;%zu;%zu\n", "PanelDockClass", sizeof(PanelDockClass), alignof(PanelDockClass));
    printf("%s;%zu;%zu\n", "PanelFrame", sizeof(PanelFrame), alignof(PanelFrame));
    printf("%s;%zu;%zu\n", "PanelFrameClass", sizeof(PanelFrameClass), alignof(PanelFrameClass));
    printf("%s;%zu;%zu\n", "PanelFrameHeaderBarClass", sizeof(PanelFrameHeaderBarClass), alignof(PanelFrameHeaderBarClass));
    printf("%s;%zu;%zu\n", "PanelFrameHeaderInterface", sizeof(PanelFrameHeaderInterface), alignof(PanelFrameHeaderInterface));
    printf("%s;%zu;%zu\n", "PanelFrameSwitcherClass", sizeof(PanelFrameSwitcherClass), alignof(PanelFrameSwitcherClass));
    printf("%s;%zu;%zu\n", "PanelFrameTabBarClass", sizeof(PanelFrameTabBarClass), alignof(PanelFrameTabBarClass));
    printf("%s;%zu;%zu\n", "PanelGSettingsActionGroupClass", sizeof(PanelGSettingsActionGroupClass), alignof(PanelGSettingsActionGroupClass));
    printf("%s;%zu;%zu\n", "PanelGrid", sizeof(PanelGrid), alignof(PanelGrid));
    printf("%s;%zu;%zu\n", "PanelGridClass", sizeof(PanelGridClass), alignof(PanelGridClass));
    printf("%s;%zu;%zu\n", "PanelGridColumnClass", sizeof(PanelGridColumnClass), alignof(PanelGridColumnClass));
    printf("%s;%zu;%zu\n", "PanelInhibitorClass", sizeof(PanelInhibitorClass), alignof(PanelInhibitorClass));
    printf("%s;%zu;%zu\n", "PanelLayeredSettingsClass", sizeof(PanelLayeredSettingsClass), alignof(PanelLayeredSettingsClass));
    printf("%s;%zu;%zu\n", "PanelMenuManagerClass", sizeof(PanelMenuManagerClass), alignof(PanelMenuManagerClass));
    printf("%s;%zu;%zu\n", "PanelOmniBar", sizeof(PanelOmniBar), alignof(PanelOmniBar));
    printf("%s;%zu;%zu\n", "PanelOmniBarClass", sizeof(PanelOmniBarClass), alignof(PanelOmniBarClass));
    printf("%s;%zu;%zu\n", "PanelPanedClass", sizeof(PanelPanedClass), alignof(PanelPanedClass));
    printf("%s;%zu;%zu\n", "PanelPositionClass", sizeof(PanelPositionClass), alignof(PanelPositionClass));
    printf("%s;%zu;%zu\n", "PanelSaveDelegate", sizeof(PanelSaveDelegate), alignof(PanelSaveDelegate));
    printf("%s;%zu;%zu\n", "PanelSaveDelegateClass", sizeof(PanelSaveDelegateClass), alignof(PanelSaveDelegateClass));
    printf("%s;%zu;%zu\n", "PanelSaveDialogClass", sizeof(PanelSaveDialogClass), alignof(PanelSaveDialogClass));
    printf("%s;%zu;%zu\n", "PanelSessionClass", sizeof(PanelSessionClass), alignof(PanelSessionClass));
    printf("%s;%zu;%zu\n", "PanelSessionItemClass", sizeof(PanelSessionItemClass), alignof(PanelSessionItemClass));
    printf("%s;%zu;%zu\n", "PanelSettingsClass", sizeof(PanelSettingsClass), alignof(PanelSettingsClass));
    printf("%s;%zu;%zu\n", "PanelStatusbarClass", sizeof(PanelStatusbarClass), alignof(PanelStatusbarClass));
    printf("%s;%zu;%zu\n", "PanelThemeSelectorClass", sizeof(PanelThemeSelectorClass), alignof(PanelThemeSelectorClass));
    printf("%s;%zu;%zu\n", "PanelToggleButtonClass", sizeof(PanelToggleButtonClass), alignof(PanelToggleButtonClass));
    printf("%s;%zu;%zu\n", "PanelWidget", sizeof(PanelWidget), alignof(PanelWidget));
    printf("%s;%zu;%zu\n", "PanelWidgetClass", sizeof(PanelWidgetClass), alignof(PanelWidgetClass));
    return 0;
}
