// Generated by gir (https://github.com/gtk-rs/gir @ 61d2f713d84d)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 46f24acbe4c2)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PanelDock", sizeof(PanelDock), alignof(PanelDock));
    printf("%s;%zu;%zu\n", "PanelDockClass", sizeof(PanelDockClass), alignof(PanelDockClass));
    printf("%s;%zu;%zu\n", "PanelDockPosition", sizeof(PanelDockPosition), alignof(PanelDockPosition));
    printf("%s;%zu;%zu\n", "PanelDockSwitcherClass", sizeof(PanelDockSwitcherClass), alignof(PanelDockSwitcherClass));
    printf("%s;%zu;%zu\n", "PanelFrame", sizeof(PanelFrame), alignof(PanelFrame));
    printf("%s;%zu;%zu\n", "PanelFrameClass", sizeof(PanelFrameClass), alignof(PanelFrameClass));
    printf("%s;%zu;%zu\n", "PanelFrameHeaderBarClass", sizeof(PanelFrameHeaderBarClass), alignof(PanelFrameHeaderBarClass));
    printf("%s;%zu;%zu\n", "PanelFrameHeaderInterface", sizeof(PanelFrameHeaderInterface), alignof(PanelFrameHeaderInterface));
    printf("%s;%zu;%zu\n", "PanelFrameSwitcherClass", sizeof(PanelFrameSwitcherClass), alignof(PanelFrameSwitcherClass));
    printf("%s;%zu;%zu\n", "PanelFrameTabBarClass", sizeof(PanelFrameTabBarClass), alignof(PanelFrameTabBarClass));
    printf("%s;%zu;%zu\n", "PanelGridClass", sizeof(PanelGridClass), alignof(PanelGridClass));
    printf("%s;%zu;%zu\n", "PanelGridColumnClass", sizeof(PanelGridColumnClass), alignof(PanelGridColumnClass));
    printf("%s;%zu;%zu\n", "PanelSaveDelegate", sizeof(PanelSaveDelegate), alignof(PanelSaveDelegate));
    printf("%s;%zu;%zu\n", "PanelSaveDelegateClass", sizeof(PanelSaveDelegateClass), alignof(PanelSaveDelegateClass));
    printf("%s;%zu;%zu\n", "PanelStatusbarClass", sizeof(PanelStatusbarClass), alignof(PanelStatusbarClass));
    printf("%s;%zu;%zu\n", "PanelWidget", sizeof(PanelWidget), alignof(PanelWidget));
    printf("%s;%zu;%zu\n", "PanelWidgetClass", sizeof(PanelWidgetClass), alignof(PanelWidgetClass));
    return 0;
}
